"""
ProjectZ - Module: WAF / CDN Detection
Fingerprints Web Application Firewalls and CDNs by:
  - HTTP response headers (Server, X-Cache, Via, CF-RAY, etc.)
  - Cookies injected by WAF (incap_ses, __cfduid, citrix_ns_id, etc.)
  - Response body signatures on crafted payloads
  - DNS CNAME chain analysis (Cloudflare, Akamai, Fastly etc.)
  - Active probe with XSS/SQLi payloads to trigger WAF block page
  - Returns: WAF name, confidence %, bypass hints, CDN name
Author: cyberhowler (R.G)
"""
from __future__ import annotations

import asyncio
import re
import socket
from urllib.parse import urlencode, quote

from src.core.engine import BaseModule
from src.core.http_client import fetch
from src.core.storage import cache, DatabaseManager
from src.core.config import config

# ── WAF fingerprints: (name, check_fn_type, pattern) ──────────────────────
# Each entry: (waf_name, source, pattern)
# source: "header", "cookie", "body", "cname"
WAF_FINGERPRINTS: list[tuple[str, str, str]] = [
    # Cloudflare
    ("Cloudflare",  "header", r"cf-ray"),
    ("Cloudflare",  "header", r"cf-cache-status"),
    ("Cloudflare",  "header", r"server:\s*cloudflare"),
    ("Cloudflare",  "cookie", r"__cfduid|__cf_bm|cf_clearance"),
    ("Cloudflare",  "body",   r"cloudflare ray id|cloudflare.*1020|attention required.*cloudflare"),
    ("Cloudflare",  "cname",  r"\.cloudflare\.com$"),
    # AWS WAF / CloudFront
    ("AWS CloudFront", "header", r"x-amz-cf-id|x-amz-cf-pop|via:.*cloudfront"),
    ("AWS WAF",        "header", r"x-amzn-requestid|x-amzn-trace-id"),
    ("AWS WAF",        "body",   r"request blocked.*aws|403 forbidden.*amazon"),
    # Akamai
    ("Akamai",      "header", r"x-check-cacheable|akamai-origin-hop|x-akamai"),
    ("Akamai",      "header", r"server:\s*akamaighost"),
    ("Akamai",      "body",   r"access denied.*akamai|reference.*akamai.*error"),
    ("Akamai",      "cname",  r"\.akamai(edge|hd|technologies)?\.net$"),
    # Imperva / Incapsula
    ("Imperva/Incapsula", "cookie", r"incap_ses|visid_incap|nlbi_"),
    ("Imperva/Incapsula", "header", r"x-iinfo|x-cdn:\s*incapsula"),
    ("Imperva/Incapsula", "body",   r"incapsula incident id|powered by incapsula"),
    # F5 BIG-IP ASM
    ("F5 BIG-IP",   "cookie", r"ts[a-f0-9]{8,}|bigipserver"),
    ("F5 BIG-IP",   "header", r"x-cnection:\s*close|x-wa-info"),
    ("F5 BIG-IP",   "body",   r"the requested url was rejected|f5 networks"),
    # Sucuri
    ("Sucuri",      "header", r"x-sucuri-id|x-sucuri-cache"),
    ("Sucuri",      "body",   r"sucuri webiste firewall|access denied.*sucuri"),
    # Barracuda
    ("Barracuda",   "header", r"barra_counter_session"),
    ("Barracuda",   "body",   r"barracuda application firewall|barracuda networks"),
    # ModSecurity
    ("ModSecurity", "header", r"mod_security|modsecurity"),
    ("ModSecurity", "body",   r"not acceptable.*mod_security|this error.*modsecurity"),
    # Wordfence (WordPress)
    ("Wordfence",   "body",   r"generated by wordfence|wordfence.*blocked"),
    # Fastly CDN
    ("Fastly",      "header", r"x-fastly-request-id|fastly-restarts|x-cache.*fastly"),
    ("Fastly",      "cname",  r"\.fastly\.net$"),
    # Varnish Cache
    ("Varnish",     "header", r"x-varnish|via:.*varnish"),
    # Nginx (generic)
    ("Nginx",       "header", r"server:\s*nginx"),
    # Fortinet FortiWeb
    ("FortiWeb",    "header", r"fortiwafsid"),
    ("FortiWeb",    "body",   r"fortiweb.*application firewall"),
    # Radware
    ("Radware",     "cookie", r"rdwr_cookie"),
    ("Radware",     "body",   r"radware.*clid|blocked by radware"),
    # DDoS-Guard
    ("DDoS-Guard",  "header", r"ddos-guard"),
    ("DDoS-Guard",  "body",   r"ddos-guard"),
    # Reblaze
    ("Reblaze",     "cookie", r"rbzid"),
    ("Reblaze",     "header", r"x-reblaze-protection"),
    # Wallarm
    ("Wallarm",     "header", r"x-wallarm-node|server:\s*nginx.*wallarm"),
    # Citrix NetScaler
    ("Citrix NetScaler", "cookie", r"ns_af=|citrix_ns_id|nthash"),
    ("Citrix NetScaler", "body",   r"netscaler.*vpn|citrix systems"),
    # Oracle Dyn
    ("Oracle Dyn",  "cname",  r"\.dynect\.net$"),
]

# Active probe payloads that trigger WAF block pages
PROBE_PAYLOADS: list[str] = [
    "/?q=<script>alert(1)</script>",
    "/?id=1' OR '1'='1",
    "/?file=../../etc/passwd",
    "/?cmd=cat+/etc/passwd",
    "/?q=../../../etc/passwd%00",
]

# Known CDN CNAME suffixes
CDN_CNAMES: dict[str, str] = {
    "cloudflare.com":   "Cloudflare",
    "akamai.net":       "Akamai",
    "akamaiedge.net":   "Akamai",
    "fastly.net":       "Fastly",
    "cloudfront.net":   "AWS CloudFront",
    "azureedge.net":    "Azure CDN",
    "llnwd.net":        "Limelight",
    "edgesuite.net":    "Akamai",
    "edgekey.net":      "Akamai",
    "footprint.net":    "CenturyLink",
}


class WAFDetectModule(BaseModule):
    MODULE_NAME = "waf"
    DESCRIPTION = "WAF/CDN fingerprinting — headers, cookies, body, DNS CNAME, active probe"

    async def run(self) -> dict:
        domain = self._clean(self.target)
        url    = f"https://{domain}"
        self.log.info(f"WAF detection: {domain}")

        cached = cache.get("waf", domain)
        if cached and not self.options.get("no_cache"):
            return cached

        result: dict = {
            "domain":         domain,
            "waf":            None,
            "cdn":            None,
            "confidence":     0,
            "bypass_hints":   [],
            "detections":     [],
            "probe_results":  [],
            "total":          0,
            "critical_findings": [],
        }

        # Run all checks concurrently
        normal_resp, probe_resps, cname_hits = await asyncio.gather(
            self._normal_request(url),
            self._active_probe(url, domain),
            self._cname_check(domain),
            return_exceptions=True,
        )

        detections: dict[str, int] = {}

        # 1 — Normal response header/cookie/body fingerprinting
        if isinstance(normal_resp, dict):
            hits = self._fingerprint_response(normal_resp)
            for waf_name in hits:
                detections[waf_name] = detections.get(waf_name, 0) + hits[waf_name]

        # 2 — Active probe results
        if isinstance(probe_resps, list):
            for pr in probe_resps:
                if isinstance(pr, dict) and pr.get("blocked"):
                    result["probe_results"].append(pr)
                    waf_name = pr.get("waf_hint", "Unknown WAF")
                    detections[waf_name] = detections.get(waf_name, 0) + 2

        # 3 — DNS CNAME check
        if isinstance(cname_hits, list):
            for hit in cname_hits:
                result["cdn"] = hit["cdn"]
                detections[hit["cdn"]] = detections.get(hit["cdn"], 0) + 3

        # Pick highest confidence WAF
        if detections:
            best    = max(detections, key=detections.get)
            max_pts = detections[best]
            confidence = min(int((max_pts / 10) * 100), 98)
            result["waf"]        = best
            result["confidence"] = confidence
            result["detections"] = [
                {"name": k, "score": v} for k, v in
                sorted(detections.items(), key=lambda x: -x[1])
            ]
            self.log.found("WAF detected", f"{best} ({confidence}% confidence)")

            # Add bypass hints based on WAF type
            result["bypass_hints"] = self._bypass_hints(best)

            result["critical_findings"].append({
                "title":    f"WAF Detected: {best}",
                "severity": "info",
                "detail":   f"Confidence: {confidence}%. Bypass hints available.",
            })
        else:
            self.log.info(f"No WAF detected for {domain}")
            result["waf"]        = "None detected"
            result["confidence"] = 0
            result["bypass_hints"] = [
                "No WAF found — consider direct injection testing",
                "Try rate-based DoS directly",
                "Look for unprotected API endpoints",
            ]

        result["total"] = len(result["detections"])
        cache.set("waf", domain, result)
        await self._persist_db(result)
        return result

    # ── Normal request ─────────────────────────────────────────────────────
    async def _normal_request(self, url: str) -> dict:
        try:
            data = await fetch(url, timeout=10, return_headers=True)
            return data if isinstance(data, dict) else {}
        except Exception:
            return {}

    # ── Active probe ───────────────────────────────────────────────────────
    async def _active_probe(self, base_url: str, domain: str) -> list:
        results = []
        for payload in PROBE_PAYLOADS[:3]:  # limit to 3 probes to stay polite
            full_url = f"https://{domain}{payload}"
            try:
                resp = await fetch(full_url, timeout=8, return_headers=True)
                if not isinstance(resp, dict):
                    continue
                status    = resp.get("status_code", 200)
                body      = (resp.get("body", "") or "").lower()
                headers   = {k.lower(): v.lower()
                             for k, v in (resp.get("headers", {}) or {}).items()}

                blocked = status in (403, 406, 429, 503) or any(
                    kw in body for kw in
                    ["access denied", "blocked", "forbidden",
                     "waf", "firewall", "security", "cloudflare ray"]
                )
                waf_hint = None
                if "cloudflare" in body or "cf-ray" in headers:
                    waf_hint = "Cloudflare"
                elif "incapsula" in body or any("incap" in c for c in headers.get("set-cookie","").split(";")):
                    waf_hint = "Imperva/Incapsula"
                elif "sucuri" in body:
                    waf_hint = "Sucuri"
                elif "akamai" in body:
                    waf_hint = "Akamai"

                results.append({
                    "payload":   payload,
                    "status":    status,
                    "blocked":   blocked,
                    "waf_hint":  waf_hint,
                })
            except Exception:
                continue
        return results

    # ── DNS CNAME check ────────────────────────────────────────────────────
    async def _cname_check(self, domain: str) -> list:
        hits = []
        try:
            loop   = asyncio.get_event_loop()
            result = await asyncio.wait_for(
                loop.run_in_executor(None, socket.getaddrinfo, domain, None),
                timeout=5,
            )
        except Exception:
            return hits

        # Try to resolve CNAME chain via dnspython if available
        try:
            import dns.resolver
            ans = dns.resolver.resolve(domain, "CNAME")
            for rdata in ans:
                cname = str(rdata.target).rstrip(".")
                for suffix, cdn_name in CDN_CNAMES.items():
                    if cname.endswith(suffix):
                        hits.append({"cname": cname, "cdn": cdn_name})
        except Exception:
            pass
        return hits

    # ── Fingerprint response ────────────────────────────────────────────────
    def _fingerprint_response(self, resp: dict) -> dict[str, int]:
        hits: dict[str, int] = {}
        headers = {k.lower(): v.lower()
                   for k, v in (resp.get("headers", {}) or {}).items()}
        body    = (resp.get("body", "") or "").lower()
        cookies = headers.get("set-cookie", "")
        header_str = " ".join(f"{k}: {v}" for k, v in headers.items())

        for (waf_name, source, pattern) in WAF_FINGERPRINTS:
            try:
                compiled = re.compile(pattern, re.I)
                target_str = {
                    "header": header_str,
                    "cookie": cookies,
                    "body":   body[:5000],
                    "cname":  "",
                }.get(source, "")
                if compiled.search(target_str):
                    hits[waf_name] = hits.get(waf_name, 0) + 1
            except Exception:
                continue
        return hits

    # ── Bypass hints ───────────────────────────────────────────────────────
    def _bypass_hints(self, waf_name: str) -> list[str]:
        hints_map: dict[str, list[str]] = {
            "Cloudflare": [
                "Try origin IP direct — find via Shodan/Censys historical SSL",
                "Use IPv6 — many CF origins have IPv6 exposed",
                "CloudFlare bypass: X-Forwarded-For: 127.0.0.1 header injection",
                "Look for subdomain with CF disabled (e.g., mail., ftp., dev.)",
                "Try crimeflare.com / leakix.net for origin IP history",
            ],
            "Imperva/Incapsula": [
                "Direct IP via SSL cert SANs (Shodan: ssl.cert.subject.CN)",
                "Try /? path with encoded payloads: %%3Cscript%%3E",
                "Rotate user-agent to Googlebot — Incapsula whitelists crawlers",
                "Use slow-rate requests to bypass rate-based detection",
            ],
            "Akamai": [
                "Try direct-to-origin via DNS history (SecurityTrails, PassiveDNS)",
                "Akamai Edge bypass: X-Forwarded-For spoofing on some configs",
                "Test non-standard ports (8080, 8443) on origin IP",
                "Use HTTP/1.0 requests — some Akamai configs don't inspect them",
            ],
            "AWS CloudFront": [
                "Find S3 origin bucket name in response headers",
                "Try /.well-known/ paths which may bypass WAF rules",
                "Look for dev/staging CloudFront distributions without WAF",
                "Use CloudFront path traversal if misconfigured origin path",
            ],
            "F5 BIG-IP": [
                "F5 iRule misconfiguration — try Cookie injection: %20OR%201=1",
                "Look for management interface on port 8443",
                "HPP (HTTP Parameter Pollution): id=1&id=2%27",
                "BIG-IP ASM bypass with multipart/form-data encoding",
            ],
            "ModSecurity": [
                "Use HPP — parameter pollution bypasses many ModSec rules",
                "Null byte injection: payload%00",
                "Encoding tricks: %%3C, %u003C, \\x3c",
                "Uncommon HTTP methods: TRACE, OPTIONS may bypass rules",
                "Content-Type: application/json often has fewer rules",
            ],
        }
        defaults = [
            "Try URL encoding: %3C instead of <",
            "Use double encoding: %253C",
            "Test with random case: <ScRiPt>",
            "Add noise characters: <scr<script>ipt>",
            "Use HTTP smuggling via chunked transfer encoding",
        ]
        return hints_map.get(waf_name, defaults)
